### ISSUE TITLE
Occasionally the commit message is being used as the attribution name.

### ISSUE THREAD

**Issue by acron0** [WorksHub/flow-bot#12]
![Screenshot_20191216_102844](https://user-images.githubusercontent.com/812199/70899884-878c8700-1fef-11ea-971b-e598edce5850.png)

This has happened a few times now, where flow-bot is using the commit message in place of the name of the original committer. 

The correct behaviour should be that the user's name is always used. If for some reason it's not available then it should be omitted.

**Comment by eckardjf** [comment]
I notice that the events are logged (debug level) before they are queued for processing - would it be possible to see an event that triggered the bug?

**Comment by acron0** [comment]
I am afraid our logs only last 7 days for this particular instance so it's not possible :( Next time it happens I will try and grab a log.

**Comment by acron0** [comment]
Typical that it hasn't happened again...
